config/routes.rb
Rails.application.routes.draw do

  get 'set/home'

  get 'set/set101'

  get 'set/set102'

  get 'set/set103'

  get 'set/set104'

  get 'registrations/update'

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get 'study/home'
  get 'study/set'

  get 'home/index'

  get 'study/index'

  resources :actual_questions

  resources :type_questions

  resources :concept_practices

  resources :concept_units

  get 'store/index'

  resources :products

  root to: 'home#index', as: 'home'

end

app/models/type_question.rb
class TypeQuestion < ActiveRecord::Base
end

app/controllers/type_questions_controller.rb
class TypeQuestionsController < ApplicationController
  before_action :set_type_question, only: [:show, :edit, :update, :destroy]

  # GET /type_questions
  # GET /type_questions.json
  def index
    @type_questions = TypeQuestion.all
  end

  # GET /type_questions/1
  # GET /type_questions/1.json
  def show
  end

  # GET /type_questions/new
  def new
    @type_question = TypeQuestion.new
  end

  # GET /type_questions/1/edit
  def edit
  end

  # POST /type_questions
  # POST /type_questions.json
  def create
    @type_question = TypeQuestion.new(type_question_params)

    respond_to do |format|
      if @type_question.save
        format.html { redirect_to @type_question, notice: 'Type question was successfully created.' }
        format.json { render :show, status: :created, location: @type_question }
      else
        format.html { render :new }
        format.json { render json: @type_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_questions/1
  # PATCH/PUT /type_questions/1.json
  def update
    respond_to do |format|
      if @type_question.update(type_question_params)
        format.html { redirect_to @type_question, notice: 'Type question was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_question }
      else
        format.html { render :edit }
        format.json { render json: @type_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_questions/1
  # DELETE /type_questions/1.json
  def destroy
    @type_question.destroy
    respond_to do |format|
      format.html { redirect_to type_questions_url, notice: 'Type question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_question
      @type_question = TypeQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_question_params
      params.require(:type_question).permit(:tq_number, :tq_question, :tq_level, :tq_answer, :tq_explanation_1, :tq_explanation_2, :tq_related_concept_1, :tq_related_concept_2, :tq_related_concept_3, :tq_related_concept_4, :tq_type_number, :tq_type_title)
    end
end

app/helpers/type_questions_helper.rb
module TypeQuestionsHelper
end

app/views/type_questions/_form.html.erb
<%= form_for(@type_question) do |f| %>
  <% if @type_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type_question.errors.count, "error") %> prohibited this type_question from being saved:</h2>

      <ul>
      <% @type_question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tq_number %><br>
    <%= f.text_field :tq_number %>
  </div>
  <div class="field">
    <%= f.label :tq_question %><br>
    <%= f.text_field :tq_question %>
  </div>
  <div class="field">
    <%= f.label :tq_level %><br>
    <%= f.text_field :tq_level %>
  </div>
  <div class="field">
    <%= f.label :tq_answer %><br>
    <%= f.text_field :tq_answer %>
  </div>
  <div class="field">
    <%= f.label :tq_explanation_1 %><br>
    <%= f.text_field :tq_explanation_1 %>
  </div>
  <div class="field">
    <%= f.label :tq_explanation_2 %><br>
    <%= f.text_field :tq_explanation_2 %>
  </div>
  <div class="field">
    <%= f.label :tq_related_concept_1 %><br>
    <%= f.text_field :tq_related_concept_1 %>
  </div>
  <div class="field">
    <%= f.label :tq_related_concept_2 %><br>
    <%= f.text_field :tq_related_concept_2 %>
  </div>
  <div class="field">
    <%= f.label :tq_related_concept_3 %><br>
    <%= f.text_field :tq_related_concept_3 %>
  </div>
  <div class="field">
    <%= f.label :tq_related_concept_4 %><br>
    <%= f.text_field :tq_related_concept_4 %>
  </div>
  <div class="field">
    <%= f.label :tq_type_number %><br>
    <%= f.text_field :tq_type_number %>
  </div>
  <div class="field">
    <%= f.label :tq_type_title %><br>
    <%= f.text_field :tq_type_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/type_questions/edit.html.erb
<h1>Editing Type Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @type_question %> |
<%= link_to 'Back', type_questions_path %>

app/views/type_questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Type Questions</h1>

<table>
  <thead>
    <tr>
      <th>Tq number</th>
      <th>Tq question</th>
      <th>Tq level</th>
      <th>Tq answer</th>
      <th>Tq explanation 1</th>
      <th>Tq explanation 2</th>
      <th>Tq related concept 1</th>
      <th>Tq related concept 2</th>
      <th>Tq related concept 3</th>
      <th>Tq related concept 4</th>
      <th>Tq type number</th>
      <th>Tq type title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_questions.each do |type_question| %>
      <tr>
        <td><%= type_question.tq_number %></td>
        <td><%= type_question.tq_question %></td>
        <td><%= type_question.tq_level %></td>
        <td><%= type_question.tq_answer %></td>
        <td><%= type_question.tq_explanation_1 %></td>
        <td><%= type_question.tq_explanation_2 %></td>
        <td><%= type_question.tq_related_concept_1 %></td>
        <td><%= type_question.tq_related_concept_2 %></td>
        <td><%= type_question.tq_related_concept_3 %></td>
        <td><%= type_question.tq_related_concept_4 %></td>
        <td><%= type_question.tq_type_number %></td>
        <td><%= type_question.tq_type_title %></td>
        <td><%= link_to 'Show', type_question %></td>
        <td><%= link_to 'Edit', edit_type_question_path(type_question) %></td>
        <td><%= link_to 'Destroy', type_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type question', new_type_question_path %>

app/views/type_questions/new.html.erb
<h1>New Type Question</h1>

<%= render 'form' %>

<%= link_to 'Back', type_questions_path %>

app/views/type_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tq number:</strong>
  <%= @type_question.tq_number %>
</p>

<p>
  <strong>Tq question:</strong>
  <%= @type_question.tq_question %>
</p>

<p>
  <strong>Tq level:</strong>
  <%= @type_question.tq_level %>
</p>

<p>
  <strong>Tq answer:</strong>
  <%= @type_question.tq_answer %>
</p>

<p>
  <strong>Tq explanation 1:</strong>
  <%= @type_question.tq_explanation_1 %>
</p>

<p>
  <strong>Tq explanation 2:</strong>
  <%= @type_question.tq_explanation_2 %>
</p>

<p>
  <strong>Tq related concept 1:</strong>
  <%= @type_question.tq_related_concept_1 %>
</p>

<p>
  <strong>Tq related concept 2:</strong>
  <%= @type_question.tq_related_concept_2 %>
</p>

<p>
  <strong>Tq related concept 3:</strong>
  <%= @type_question.tq_related_concept_3 %>
</p>

<p>
  <strong>Tq related concept 4:</strong>
  <%= @type_question.tq_related_concept_4 %>
</p>

<p>
  <strong>Tq type number:</strong>
  <%= @type_question.tq_type_number %>
</p>

<p>
  <strong>Tq type title:</strong>
  <%= @type_question.tq_type_title %>
</p>

<%= link_to 'Edit', edit_type_question_path(@type_question) %> |
<%= link_to 'Back', type_questions_path %>