config/routes.rb
Rails.application.routes.draw do

  get 'set/home'

  get 'set/set101'

  get 'set/set102'

  get 'set/set103'

  get 'set/set104'

  get 'registrations/update'

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get 'study/home'
  get 'study/set'

  get 'home/index'

  get 'study/index'

  resources :actual_questions

  resources :type_questions

  resources :concept_practices

  resources :concept_units

  get 'store/index'

  resources :products

  root to: 'home#index', as: 'home'

end

app/models/concept_unit.rb
class ConceptUnit < ActiveRecord::Base
end

app/controllers/concept_units_controller.rb
class ConceptUnitsController < ApplicationController
  before_action :set_concept_unit, only: [:show, :edit, :update, :destroy]

  # GET /concept_units
  # GET /concept_units.json
  def index
    @concept_units = ConceptUnit.all
  end

  # GET /concept_units/1
  # GET /concept_units/1.json
  def show
  end

  # GET /concept_units/new
  def new
    @concept_unit = ConceptUnit.new
  end

  # GET /concept_units/1/edit
  def edit
  end

  # POST /concept_units
  # POST /concept_units.json
  def create
    @concept_unit = ConceptUnit.new(concept_unit_params)

    respond_to do |format|
      if @concept_unit.save
        format.html { redirect_to @concept_unit, notice: 'Concept unit was successfully created.' }
        format.json { render :show, status: :created, location: @concept_unit }
      else
        format.html { render :new }
        format.json { render json: @concept_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concept_units/1
  # PATCH/PUT /concept_units/1.json
  def update
    respond_to do |format|
      if @concept_unit.update(concept_unit_params)
        format.html { redirect_to @concept_unit, notice: 'Concept unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @concept_unit }
      else
        format.html { render :edit }
        format.json { render json: @concept_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concept_units/1
  # DELETE /concept_units/1.json
  def destroy
    @concept_unit.destroy
    respond_to do |format|
      format.html { redirect_to concept_units_url, notice: 'Concept unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concept_unit
      @concept_unit = ConceptUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concept_unit_params
      params.require(:concept_unit).permit(:cu_number, :cu_title, :cu_description, :cu_level, :cu_concept, :cu_explanation_1, :cu_explanation_2, :cu_reference_1, :cu_reference_2, :exercise_blpr_1, :exercise_blan_1, :exercise_blpr_2, :exercise_blan_2, :exercise_blpr_3, :exercise_blan_3, :exercise_rwpr_1, :exercise_rwan_1, :exercise_rwpr_2, :exercise_rwan_2)
    end
end

app/helpers/concept_units_helper.rb
module ConceptUnitsHelper
end

app/views/concept_units/_form.html.erb
<%= form_for(@concept_unit) do |f| %>
  <% if @concept_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concept_unit.errors.count, "error") %> prohibited this concept_unit from being saved:</h2>

      <ul>
      <% @concept_unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cu_number %><br>
    <%= f.text_field :cu_number %>
  </div>
  <div class="field">
    <%= f.label :cu_title %><br>
    <%= f.text_field :cu_title %>
  </div>
  <div class="field">
    <%= f.label :cu_description %><br>
    <%= f.text_area :cu_description %>
  </div>
  <div class="field">
    <%= f.label :cu_level %><br>
    <%= f.text_field :cu_level %>
  </div>
  <div class="field">
    <%= f.label :cu_concept %><br>
    <%= f.text_field :cu_concept %>
  </div>
  <div class="field">
    <%= f.label :cu_explanation_1 %><br>
    <%= f.text_field :cu_explanation_1 %>
  </div>
  <div class="field">
    <%= f.label :cu_explanation_2 %><br>
    <%= f.text_field :cu_explanation_2 %>
  </div>
  <div class="field">
    <%= f.label :cu_reference_1 %><br>
    <%= f.text_field :cu_reference_1 %>
  </div>
  <div class="field">
    <%= f.label :cu_reference_2 %><br>
    <%= f.text_field :cu_reference_2 %>
  </div>
  <div class="field">
    <%= f.label :exercise_blpr_1 %><br>
    <%= f.text_field :exercise_blpr_1 %>
  </div>
  <div class="field">
    <%= f.label :exercise_blan_1 %><br>
    <%= f.text_field :exercise_blan_1 %>
  </div>
  <div class="field">
    <%= f.label :exercise_blpr_2 %><br>
    <%= f.text_field :exercise_blpr_2 %>
  </div>
  <div class="field">
    <%= f.label :exercise_blan_2 %><br>
    <%= f.text_field :exercise_blan_2 %>
  </div>
  <div class="field">
    <%= f.label :exercise_blpr_3 %><br>
    <%= f.text_field :exercise_blpr_3 %>
  </div>
  <div class="field">
    <%= f.label :exercise_blan_3 %><br>
    <%= f.text_field :exercise_blan_3 %>
  </div>
  <div class="field">
    <%= f.label :exercise_rwpr_1 %><br>
    <%= f.text_field :exercise_rwpr_1 %>
  </div>
  <div class="field">
    <%= f.label :exercise_rwan_1 %><br>
    <%= f.text_field :exercise_rwan_1 %>
  </div>
  <div class="field">
    <%= f.label :exercise_rwpr_2 %><br>
    <%= f.text_field :exercise_rwpr_2 %>
  </div>
  <div class="field">
    <%= f.label :exercise_rwan_2 %><br>
    <%= f.text_field :exercise_rwan_2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concept_units/edit.html.erb
<h1>Editing Concept Unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @concept_unit %> |
<%= link_to 'Back', concept_units_path %>

app/views/concept_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Concept Units</h1>

<table>
  <thead>
    <tr>
      <th>Cu number</th>
      <th>Cu title</th>
      <th>Cu description</th>
      <th>Cu level</th>
      <th>Cu concept</th>
      <th>Cu explanation 1</th>
      <th>Cu explanation 2</th>
      <th>Cu reference 1</th>
      <th>Cu reference 2</th>
      <th>Exercise blpr 1</th>
      <th>Exercise blan 1</th>
      <th>Exercise blpr 2</th>
      <th>Exercise blan 2</th>
      <th>Exercise blpr 3</th>
      <th>Exercise blan 3</th>
      <th>Exercise rwpr 1</th>
      <th>Exercise rwan 1</th>
      <th>Exercise rwpr 2</th>
      <th>Exercise rwan 2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concept_units.each do |concept_unit| %>
      <tr>
        <td><%= concept_unit.cu_number %></td>
        <td><%= concept_unit.cu_title %></td>
        <td><%= concept_unit.cu_description %></td>
        <td><%= concept_unit.cu_level %></td>
        <td><%= concept_unit.cu_concept %></td>
        <td><%= concept_unit.cu_explanation_1 %></td>
        <td><%= concept_unit.cu_explanation_2 %></td>
        <td><%= concept_unit.cu_reference_1 %></td>
        <td><%= concept_unit.cu_reference_2 %></td>
        <td><%= concept_unit.exercise_blpr_1 %></td>
        <td><%= concept_unit.exercise_blan_1 %></td>
        <td><%= concept_unit.exercise_blpr_2 %></td>
        <td><%= concept_unit.exercise_blan_2 %></td>
        <td><%= concept_unit.exercise_blpr_3 %></td>
        <td><%= concept_unit.exercise_blan_3 %></td>
        <td><%= concept_unit.exercise_rwpr_1 %></td>
        <td><%= concept_unit.exercise_rwan_1 %></td>
        <td><%= concept_unit.exercise_rwpr_2 %></td>
        <td><%= concept_unit.exercise_rwan_2 %></td>
        <td><%= link_to 'Show', concept_unit %></td>
        <td><%= link_to 'Edit', edit_concept_unit_path(concept_unit) %></td>
        <td><%= link_to 'Destroy', concept_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concept unit', new_concept_unit_path %>

app/views/concept_units/new.html.erb
<h1>New Concept Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', concept_units_path %>

app/views/concept_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cu number:</strong>
  <%= @concept_unit.cu_number %>
</p>

<p>
  <strong>Cu title:</strong>
  <%= @concept_unit.cu_title %>
</p>

<p>
  <strong>Cu description:</strong>
  <%= @concept_unit.cu_description %>
</p>

<p>
  <strong>Cu level:</strong>
  <%= @concept_unit.cu_level %>
</p>

<p>
  <strong>Cu concept:</strong>
  <%= @concept_unit.cu_concept %>
</p>

<p>
  <strong>Cu explanation 1:</strong>
  <%= @concept_unit.cu_explanation_1 %>
</p>

<p>
  <strong>Cu explanation 2:</strong>
  <%= @concept_unit.cu_explanation_2 %>
</p>

<p>
  <strong>Cu reference 1:</strong>
  <%= @concept_unit.cu_reference_1 %>
</p>

<p>
  <strong>Cu reference 2:</strong>
  <%= @concept_unit.cu_reference_2 %>
</p>

<p>
  <strong>Exercise blpr 1:</strong>
  <%= @concept_unit.exercise_blpr_1 %>
</p>

<p>
  <strong>Exercise blan 1:</strong>
  <%= @concept_unit.exercise_blan_1 %>
</p>

<p>
  <strong>Exercise blpr 2:</strong>
  <%= @concept_unit.exercise_blpr_2 %>
</p>

<p>
  <strong>Exercise blan 2:</strong>
  <%= @concept_unit.exercise_blan_2 %>
</p>

<p>
  <strong>Exercise blpr 3:</strong>
  <%= @concept_unit.exercise_blpr_3 %>
</p>

<p>
  <strong>Exercise blan 3:</strong>
  <%= @concept_unit.exercise_blan_3 %>
</p>

<p>
  <strong>Exercise rwpr 1:</strong>
  <%= @concept_unit.exercise_rwpr_1 %>
</p>

<p>
  <strong>Exercise rwan 1:</strong>
  <%= @concept_unit.exercise_rwan_1 %>
</p>

<p>
  <strong>Exercise rwpr 2:</strong>
  <%= @concept_unit.exercise_rwpr_2 %>
</p>

<p>
  <strong>Exercise rwan 2:</strong>
  <%= @concept_unit.exercise_rwan_2 %>
</p>

<%= link_to 'Edit', edit_concept_unit_path(@concept_unit) %> |
<%= link_to 'Back', concept_units_path %>