config/routes.rb
Rails.application.routes.draw do

  get 'set/home'

  get 'set/set101'

  get 'set/set102'

  get 'set/set103'

  get 'set/set104'

  get 'registrations/update'

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get 'study/home'
  get 'study/set'

  get 'home/index'

  get 'study/index'

  resources :actual_questions

  resources :type_questions

  resources :concept_practices

  resources :concept_units

  get 'store/index'

  resources :products

  root to: 'home#index', as: 'home'

end

app/models/concept_practice.rb
class ConceptPractice < ActiveRecord::Base
end

app/controllers/concept_practices_controller.rb
class ConceptPracticesController < ApplicationController
  before_action :set_concept_practice, only: [:show, :edit, :update, :destroy]

  # GET /concept_practices
  # GET /concept_practices.json
  def index
    @concept_practices = ConceptPractice.all
  end

  # GET /concept_practices/1
  # GET /concept_practices/1.json
  def show
  end

  # GET /concept_practices/new
  def new
    @concept_practice = ConceptPractice.new
  end

  # GET /concept_practices/1/edit
  def edit
  end

  # POST /concept_practices
  # POST /concept_practices.json
  def create
    @concept_practice = ConceptPractice.new(concept_practice_params)

    respond_to do |format|
      if @concept_practice.save
        format.html { redirect_to @concept_practice, notice: 'Concept practice was successfully created.' }
        format.json { render :show, status: :created, location: @concept_practice }
      else
        format.html { render :new }
        format.json { render json: @concept_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concept_practices/1
  # PATCH/PUT /concept_practices/1.json
  def update
    respond_to do |format|
      if @concept_practice.update(concept_practice_params)
        format.html { redirect_to @concept_practice, notice: 'Concept practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @concept_practice }
      else
        format.html { render :edit }
        format.json { render json: @concept_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concept_practices/1
  # DELETE /concept_practices/1.json
  def destroy
    @concept_practice.destroy
    respond_to do |format|
      format.html { redirect_to concept_practices_url, notice: 'Concept practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concept_practice
      @concept_practice = ConceptPractice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concept_practice_params
      params.require(:concept_practice).permit(:cp_number, :cp_question, :cp_answer, :cp_explanation)
    end
end

app/helpers/concept_practices_helper.rb
module ConceptPracticesHelper
end

app/views/concept_practices/_form.html.erb
<%= form_for(@concept_practice) do |f| %>
  <% if @concept_practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concept_practice.errors.count, "error") %> prohibited this concept_practice from being saved:</h2>

      <ul>
      <% @concept_practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cp_number %><br>
    <%= f.text_field :cp_number %>
  </div>
  <div class="field">
    <%= f.label :cp_question %><br>
    <%= f.text_field :cp_question %>
  </div>
  <div class="field">
    <%= f.label :cp_answer %><br>
    <%= f.text_field :cp_answer %>
  </div>
  <div class="field">
    <%= f.label :cp_explanation %><br>
    <%= f.text_field :cp_explanation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concept_practices/edit.html.erb
<h1>Editing Concept Practice</h1>

<%= render 'form' %>

<%= link_to 'Show', @concept_practice %> |
<%= link_to 'Back', concept_practices_path %>

app/views/concept_practices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Concept Practices</h1>

<table>
  <thead>
    <tr>
      <th>Cp number</th>
      <th>Cp question</th>
      <th>Cp answer</th>
      <th>Cp explanation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concept_practices.each do |concept_practice| %>
      <tr>
        <td><%= concept_practice.cp_number %></td>
        <td><%= concept_practice.cp_question %></td>
        <td><%= concept_practice.cp_answer %></td>
        <td><%= concept_practice.cp_explanation %></td>
        <td><%= link_to 'Show', concept_practice %></td>
        <td><%= link_to 'Edit', edit_concept_practice_path(concept_practice) %></td>
        <td><%= link_to 'Destroy', concept_practice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concept practice', new_concept_practice_path %>

app/views/concept_practices/new.html.erb
<h1>New Concept Practice</h1>

<%= render 'form' %>

<%= link_to 'Back', concept_practices_path %>

app/views/concept_practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cp number:</strong>
  <%= @concept_practice.cp_number %>
</p>

<p>
  <strong>Cp question:</strong>
  <%= @concept_practice.cp_question %>
</p>

<p>
  <strong>Cp answer:</strong>
  <%= @concept_practice.cp_answer %>
</p>

<p>
  <strong>Cp explanation:</strong>
  <%= @concept_practice.cp_explanation %>
</p>

<%= link_to 'Edit', edit_concept_practice_path(@concept_practice) %> |
<%= link_to 'Back', concept_practices_path %>